---
# Source: mariadb/templates/rolebinding.yaml

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mariadb
  labels:
    app: "mariadb"
    chart: "mariadb-7.3.5"
    release: "mariadb"
    heritage: "Tiller"
subjects:
- kind: ServiceAccount
  name: mariadb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mariadb
