---
# Source: mariadb/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mariadb
  labels:
    app: "mariadb"
    chart: "mariadb-7.3.5"
    release: "mariadb"
    heritage: "Helm"
type: Opaque
data:
  mariadb-root-password: "c3VzZWNvbg=="
