---
# Source: mariadb/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mariadb
  labels:
    app: "mariadb"
    chart: "mariadb-7.3.5"
    release: "mariadb"
    heritage: "Helm"
