---
# Source: local-path-provisioner/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: local-path-provisioner
  labels:
    app.kubernetes.io/name: local-path-provisioner
    helm.sh/chart: local-path-provisioner-0.0.12
    app.kubernetes.io/instance: local-path-provisioner
    app.kubernetes.io/version: "v0.0.12"
    app.kubernetes.io/managed-by: Helm
data:
apiVersion: v1
data:
  config.json: |-
    {
      "nodePathMap": 
        [
          {
            "node": "DEFAULT_PATH_FOR_NON_LISTED_NODES",
            "paths": [
              "/opt/local-path-provisioner"
            ]
          }
        ]
    }
