---
# Source: local-path-provisioner/templates/storageclass.yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-path
  labels:
    app.kubernetes.io/name: local-path-provisioner
    helm.sh/chart: local-path-provisioner-0.0.12
    app.kubernetes.io/instance: local-path-provisioner
    app.kubernetes.io/version: "v0.0.12"
    app.kubernetes.io/managed-by: Tiller
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: cluster.local/local-path-provisioner
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
