prestashopHost: prestashop.susecon.lab
prestashopEmail: susecon@suse.com
prestashopPassword: susecon
prestashopFirstName: Suse
prestashopLastName: Con

prestashopCountry: "us"

externalDatabase:
  host: mariadb.mariadb.svc.cluster.local
  port: 3306
  user: prestashop
  password: susecon
  database: prestashop

mariadb:
  enabled: false

service:
  type: LoadBalancer
  port: 80
  httpsPort: 443
  nodePorts: {}

persistence:
  enabled: true
  storageClass: local-path

metrics:
  enabled: true
