alertmanager:
  enabled: false
kubeStateMetrics:
  enabled: true
nodeExporter:
  enabled: true
pushgateway:
  enabled: false
server:
  persistentVolume:
    accessModes:
    - ReadWriteOnce
    enabled: true
    storageClass: local-path
