adminPassword: susecon
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - access: proxy
      isDefault: true
      name: Prometheus
      orgId: 1
      type: prometheus
      url: http://prometheus-server
    deleteDatasources:
    - name: Prometheus
      orgId: 1
#ingress:
#  annotations:
#    kubernetes.io/ingress.class: nginx
#  enabled: true
#  hosts:
#  - grafana.192.168.73.165.omg.howdoi.website
persistence:
  enabled: true
  size: 5Gi
  storageClassName: local-path
rbac:
  create: true
service:
  nodePort: 30030
  servicePort: 80
  type: NodePort
sidecar:
  dashboards:
    enabled: true
    label: grafana_dashboard
