alertmanager:
  enabled: false
#extraScrapeConfigs: |
#  - job_name: kobay_prometheus-node-exporter
#    relabel_configs:
#    - source_labels:
#      - __address__
#      target_label: kubernetes_node
#    - replacement: $1:30091
#      source_labels:
#      - __address__
#      target_label: __address__
#    scrape_interval: 5s
#    static_configs:
#    - targets:
#      - 192.168.73.128
#      - 192.168.72.102
#      - 192.168.72.182
#      - 192.168.73.114
kubeStateMetrics:
  enabled: true
nodeExporter:
  enabled: true
pushgateway:
  enabled: false
server:
#  ingress:
#    annotations:
#      kubernetes.io/ingress.class: nginx
#    enabled: true
#    hosts:
#    - prometheus-server.192.168.73.165.omg.howdoi.website
  persistentVolume:
    accessModes:
    - ReadWriteOnce
    enabled: true
    storageClass: local-path
  service:
    nodePort: 30090
    servicePort: 80
    type: NodePort
