---
apiVersion: v1
kind: Namespace
metadata:
  name: envoy
---
apiVersion: v1
kind: Namespace
metadata:
  name: logging
---
apiVersion: v1
kind: Namespace
metadata:
  name: mariadb
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: v1
kind: Namespace
metadata:
  name: nextcloud
---
apiVersion: v1
kind: Namespace
metadata:
  name: prestashop
---
apiVersion: v1
kind: Namespace
metadata:
  name: tblshoot
