---
# Source: envoy/templates/service.yaml

apiVersion: v1
kind: Service
metadata:
  name: envoy
  labels:
    app: envoy
    chart: envoy-1.9.0
    release: envoy
    heritage: Tiller
  annotations:
spec:
  type: ClusterIP
  ports:
    - name: n0
      port: 80
      protocol: TCP
      targetPort: n0
      
    - name: n1
      port: 443
      protocol: TCP
      targetPort: n1
      
    - name: n2
      port: 3306
      protocol: TCP
      targetPort: n2
      
  selector:
    app: envoy
    release: envoy
