---
# Source: grafana/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana
  namespace: monitoring
  labels:
    app: grafana
    chart: grafana-4.3.2
    release: grafana
    heritage: Helm
data:
  grafana.ini: |
    [analytics]
    check_for_updates = true
    [grafana_net]
    url = https://grafana.net
    [log]
    mode = console
    [paths]
    data = /var/lib/grafana/data
    logs = /var/log/grafana
    plugins = /var/lib/grafana/plugins
    provisioning = /etc/grafana/provisioning

  datasources.yaml: |
    apiVersion: 1
    datasources:
    - access: proxy
      isDefault: true
      name: Prometheus
      orgId: 1
      type: prometheus
      url: http://prometheus-server.monitoring.svc.cluster.local
    - access: proxy
      isDefault: false
      name: Loki
      orgId: 1
      type: loki
      url: http://loki.logging.svc.cluster.local:3100
    deleteDatasources:
    - name: Prometheus
      orgId: 1
    - name: Loki
      orgId: 1
