---
# Source: grafana/templates/secret.yaml

apiVersion: v1
kind: Secret
metadata:
  name: grafana
  namespace: monitoring
  labels:
    app: grafana
    chart: grafana-4.3.2
    release: grafana
    heritage: Tiller
type: Opaque
data:
  admin-user: "YWRtaW4="
  admin-password: "c3VzZWNvbg=="
  ldap-toml: ""
