---
# Source: prometheus/templates/server-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    component: "server"
    app: prometheus
    release: prometheus
    chart: prometheus-10.3.1
    heritage: Tiller
  name: prometheus-server
spec:
  accessModes:
    - ReadWriteOnce
    
  storageClassName: "local-path"
  resources:
    requests:
      storage: "8Gi"