---
# Source: nextcloud/templates/db-secret.yaml

apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-db
  labels:
    app.kubernetes.io/name: nextcloud
    helm.sh/chart: nextcloud-1.9.1
    app.kubernetes.io/instance: nextcloud
    app.kubernetes.io/managed-by: Tiller
type: Opaque
data:
  db-password: "bmV4dGNsb3Vk"
  db-username: "bmV4dGNsb3Vk"
