---
# Source: nextcloud/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: nextcloud
  labels:
    app.kubernetes.io/name: nextcloud
    helm.sh/chart: nextcloud-1.9.1
    app.kubernetes.io/instance: nextcloud
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  nextcloud-username: "YWRtaW4="
  
  nextcloud-password: "c3VzZWNvbg=="
