---
# Source: prestashop/templates/externaldb-secrets.yaml

apiVersion: v1
kind: Secret
metadata:
  name: "prestashop-externaldb"
  labels:
    app: "prestashop-externaldb"
    chart: "prestashop-9.1.3"
    release: "prestashop"
    heritage: "Tiller"
type: Opaque
data:
  db-password: "cHJlc3Rhc2hvcA=="
