---
# Source: prestashop/templates/prestashop-pvc.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: prestashop-prestashop
  labels:
    app: "prestashop"
    chart: "prestashop-9.1.3"
    release: "prestashop"
    heritage: "Helm"
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "8Gi"
  storageClassName: local-path
