---
# Source: prestashop/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: prestashop
  labels:
    app: "prestashop"
    chart: "prestashop-9.1.3"
    release: "prestashop"
    heritage: "Tiller"
  annotations:
    "helm.sh/hook": pre-install    
type: Opaque
data:
  prestashop-password: "c3VzZWNvbg=="
