---
# Source: prestashop/templates/svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: prestashop
  labels:
    app: "prestashop"
    chart: "prestashop-9.1.3"
    release: "prestashop"
    heritage: "Helm"
spec:
  type: LoadBalancer
  externalTrafficPolicy: "Local"
  ports:
    - name: http
      port: 80
      targetPort: http
    - name: https
      port: 443
      targetPort: https
  selector:
    app: "prestashop"
    release: "prestashop"
