---
# Source: promtail/templates/serviceaccount.yaml

apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: promtail
    chart: promtail-0.19.1
    heritage: Tiller
    release: promtail
  name: promtail
  namespace: logging

